apiVersion: v1
kind: Pod
metadata:
  name: keepalived
  namespace: kube-system
spec:
  containers:
  - image: osixia/keepalived:1.3.5-1
    name: keepalived
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_BROADCAST
        - NET_RAW
    volumeMounts:
    - name: config
      mountPath: /usr/local/etc/keepalived/keepalived.conf
    - name: check
      mountPath: /etc/keepalived/check_apiserver.sh
  hostNetwork: true
  volumes:
  - name: config
    hostPath:
      path: /usr/local/etc/keepalived.conf
  - name: check
    hostPath:
      path: /usr/local/etc/check_apiserver.sh   
status: {}
